name: release

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  terUpload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: sitegeist/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
